# Generated by Django 5.1.4 on 2025-02-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
