# Generated by Django 5.1.4 on 2025-02-13 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_feed_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed_post',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category'),
        ),
    ]
