# Generated by Django 5.1.4 on 2025-02-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_feed_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chhand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/')),
                ('lyrics', models.TextField()),
                ('translation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category')),
            ],
        ),
    ]
