# Generated by Django 5.1.4 on 2025-02-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_chhand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
    ]
